### ISSUE TITLE
q set as 0.1 but used with 1.0

### ISSUE THREAD

**Issue by brumar** [Networks-Learning/memorize#1]
Hello,
Thanks for sharing your code!
`q = 0.1` is defined at the top level of `memorize.py`, but sampler is called in the `sampler` function with the value `q = 1.0`.

Also, I have some difficulties to match what I understood by rate and what `sampler` do.
Sampler seems to pick a random date in the future, compute the intensity at this date, then decide whether or not it will be scheduled at this date. Is this right? My understanding of rate would give rather something like : 
```python
[...]
t=0
while t < MAX_DURATION:
    t = t + 1
    rate = compute_rate(t, [...])
    pbt = 1/rate
    if random.uniform() < pbt:
        return t
return None
```

**Comment by btabibian** [comment]
@brumar Thanks for pointing out the bug. It is now fixed in the code.

The sampler is using a method known as thinning algorithm for sampling from in-homogenous Poisson Processes, for an explanation of this method you can look [here](https://www.math.fsu.edu/~ychen/research/Thinning%20algorithm.pdf) and Algorithm 2.

In a nutshell, to sample from an inhomogenous Poisson Proccess with intensity $\lambda*(t)$, this algorithm first samples an event time, $t'$, from a homogenous Poisson Process with an intensity $\lambda=sup_t  \lambda*(t)$ where $sup$ indicates supremum of a function. Then accepts the proposed event timing with probability $\lambda*(t')/\lambda$ or rejects otherwise.

I hope this clarifies your question. Please let me know if you had any more questions.

**Comment by brumar** [comment]
Wow, that's an interesting one! Thank you!

**Comment by btabibian** [comment]
I will close the issue. let me know if there was any other problems.
